export const CLIENT_LIST_REQUEST = "CLIENT_LIST_REQUEST";
export const CLIENT_LIST_SUCCESS = "CLIENT_LIST_SUCCESS";
export const CLIENT_LIST_FAIL = "CLIENT_LIST_FAIL";

export const CLIENT_REGISTER_REQUEST = "CLIENT_REGISTER_REQUEST";
export const CLIENT_REGISTER_SUCCESS = "CLIENT_REGISTER_SUCCESS";
export const CLIENT_REGISTER_FAIL = "CLIENT_REGISTER_FAIL";

export const CLIENT_DELETE_REQUEST = "CLIENT_DELETE_REQUEST";
export const CLIENT_DELETE_SUCCESS = "CLIENT_DELETE_SUCCESS";
export const CLIENT_DELETE_FAIL = "CLIENT_DELETE_FAIL";

export const CLIENT_UPDATE_REQUEST = "CLIENT_UPDATE_REQUEST";
export const CLIENT_UPDATE_SUCCESS = "CLIENT_UPDATE_SUCCESS";
export const CLIENT_UPDATE_FAIL = "CLIENT_UPDATE_FAIL";

export const CLIENT_GET_DETAILS_REQUEST = "CLIENT_GET_DETAILS_REQUEST";
export const CLIENT_GET_DETAILS_SUCCESS = "CLIENT_GET_DETAILS_SUCCESS";
export const CLIENT_GET_DETAILS_FAIL = "CLIENT_GET_DETAILS_FAIL";
