export const TEACHER_LIST_REQUEST = "TEACHER_LIST_REQUEST";
export const TEACHER_LIST_SUCCESS = "TEACHER_LIST_SUCCESS";
export const TEACHER_LIST_FAIL = "TEACHER_LIST_FAIL";

export const TEACHER_REGISTER_REQUEST = "TEACHER_REGISTER_REQUEST";
export const TEACHER_REGISTER_SUCCESS = "TEACHER_REGISTER_SUCCESS";
export const TEACHER_REGISTER_FAIL = "TEACHER_REGISTER_FAIL";
